apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    field.cattle.io/displayName: hpa-insecure
  name: hpa-insecure
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: insecured
  targetCPUUtilizationPercentage: 10

