apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-123
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: ra-demo2
  targetCPUUtilizationPercentage: 1
status:
  currentReplicas: 1
  desiredReplicas: 0
