apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secured
  name: secured
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secured
  template:
    metadata:
      labels:
        app: secured
    spec:
      containers:
      - image: docker.io/thecrazyrussian/ra-demo:1
        imagePullPolicy: Always
        name: secured
        ports:
        - containerPort: 80
          name: 80tcp2
          protocol: TCP
        resources: 
          limits:
            cpu: 200m
          requests:
            cpu: 200m 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      priorityClassName: high-priority
