---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra-demo2
  labels:
    app: ra-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ra-demo2
  template:
    metadata:
      labels:
        app: ra-demo2
    spec:
      containers:
      - name: ra-demo2
        image: docker.io/thecrazyrussian/ra-demo:1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
