apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ra-demo"},"name":"ra-demo","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ra-demo"}},"template":{"metadata":{"labels":{"app":"ra-demo"}},"spec":{"containers":[{"image":"docker.io/thecrazyrussian/ra-demo:1","imagePullPolicy":"Always","name":"ra-demo","ports":[{"containerPort":80}]}]}}}}'
  creationTimestamp: "2020-05-14T16:11:41Z"
  generation: 4
  labels:
    app: ra-demo
  name: ra-demo
  namespace: default
  resourceVersion: "687188"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ra-demo
  uid: af90d60d-4ae5-4fed-9a33-d034cd774b32
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ra-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-14T16:28:55Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"ra-demo","hostPort":0,"kind":"ClusterIP","name":"80tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        app: ra-demo
    spec:
      containers:
      - image: docker.io/thecrazyrussian/ra-demo:1
        imagePullPolicy: Always
        name: ra-demo
        ports:
        - containerPort: 80
          name: 80tcp02
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: 
        privileged: true
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-05-14T16:47:59Z"
    lastUpdateTime: "2020-05-14T16:47:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-14T16:11:41Z"
    lastUpdateTime: "2020-05-14T16:49:24Z"
    message: ReplicaSet "ra-demo-555676489b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
